### ISSUE TITLE
Navegação 

### ISSUE THREAD

**Issue by Brendo-William-DEV** [Brendo-William-DEV/ads031#17]
A quis era feito a verificação de navegação do site.

**Comment by Pauloviictorss** [comment]
Opa, a navegação entre as telas de notícias relacionadas à criptomoedas já foi feita!
Segue o código compactado em formato ZIP abaixo:

[CriptoNews.zip](https://github.com/Brendo-William-DEV/ads031/files/7373170/CriptoNews.zip)
