### ISSUE TITLE
Criar categoria de pagina de noticia como tema Mercado Financeiros 

### ISSUE THREAD

**Issue by Brendo-William-DEV** [Brendo-William-DEV/ads031#6]
Escolha e disserte sobre 2 notícias de sua categoria
Selecionar imagens de Categorias.
Organizar o funcionamento de sua página e verificar se está responsiva

**Comment by victor2706** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/61297694/132283149-e2213f93-18dc-4f52-ba63-1c671dec6bf3.png)

Categoria das noticias d Tema "Mercado Financeiro" Feito!!!
