### ISSUE TITLE
Criar categoria de pagina de noticia como tema Jogos Console 

### ISSUE THREAD

**Issue by Brendo-William-DEV** [Brendo-William-DEV/ads031#7]
Escolha e disserte sobre 2 notícias de sua categoria
Selecionar imagens de Categorias.
Organizar o funcionamento de sua página e verificar se está responsiva

**Comment by Batatazim** [comment]
tudo pronto por hora

**Comment by Brendo-William-DEV** [comment]
![image](https://user-images.githubusercontent.com/86269955/134246811-9e09c4c9-da9b-45e8-92f1-6100c26a9450.png)
